/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#88d982',
        'on-primary-fixed': '#380d00',
        secondary: '#5f5e5e',
        'inverse-surface': '#2f312f',
        'surface-container-low': '#f4f4f1',
        'surface-variant': '#e2e3e0',
        'on-surface-variant': '#5a4138',
        'outline-variant': '#e3bfb2',
        tertiary: '#186a22',
        'on-secondary-container': '#656464',
        'on-surface': '#1a1c1b',
        'on-tertiary-fixed-variant': '#005312',
        'on-primary-container': '#fffbff',
        'on-secondary-fixed-variant': '#474747',
        outline: '#8f7066',
        'on-error-container': '#93000a',
        'surface-container-highest': '#e2e3e0',
        'on-tertiary': '#ffffff',
        'secondary-fixed': '#e4e2e1',
        'inverse-on-surface': '#f1f1ee',
        'on-primary-fixed-variant': '#802a00',
        'on-secondary-fixed': '#1b1c1c',
        'secondary-fixed-dim': '#c8c6c6',
        'secondary-container': '#e4e2e1',
        'surface-container-high': '#e8e8e5',
        'primary-container': '#cd4700',
        'surface-container-lowest': '#ffffff',
        'on-background': '#1a1c1b',
        'on-tertiary-fixed': '#002204',
        'error-container': '#ffdad6',
        'primary-fixed-dim': '#ffb59a',
        background: '#f9f9f6',
        'on-primary': '#ffffff',
        'on-tertiary-container': '#f7fff1',
        'surface-container': '#eeeeeb',
        error: '#ba1a1a',
        surface: '#f9f9f6',
        'inverse-primary': '#ffb59a',
        'surface-dim': '#dadad7',
        'tertiary-container': '#358438',
        'surface-tint': '#a83900',
        'tertiary-fixed': '#a3f69c',
        'on-secondary': '#ffffff',
        'primary-fixed': '#ffdbcf',
        'on-error': '#ffffff',
        primary: '#a43700',
        'surface-bright': '#f9f9f6',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: [
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          'Liberation Mono',
          'Courier New',
          'monospace',
        ],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
